name: left-ci
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  # - either >= 5
  - mtl
  - text
  - containers

library:
  source-dirs: src
  exposed-modules:
    - Config.ApplicationConfig
    - Config.Validator
    - Server.Service
    - Server.Service.Persistent
    - Server.DataStore
    - Server.DataStore.Atomic
    - Server.DataStore.SQLiteBuildStore
    - Server.Routes
    - Server.Domain
  dependencies:
    - directory
    - network
    - scotty
    - wai
    - http-types 
    - warp
    - aeson
    - bytestring
    - sqlite-simple
    - resource-pool

executables:
  left-ci:
    main: Main.hs
    source-dirs: app
    dependencies:
      - left-ci
      - warp



tests:
  unit:
    dependencies:
      - left-ci
      - HUnit
    main: Main.hs
    source-dirs: test/unit

  integration:
    dependencies:
      - left-ci
      - HUnit
      - directory
      - network
      - wai
      - bytestring
      - wai-extra
      - http-types
      - scotty
      - aeson
      - sqlite-simple
      - resource-pool
    main: Main.hs
    source-dirs: test/integration
