name: left-ci
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers

library:
  source-dirs: src
  exposed-modules:
    - Server.App
    - Server.Routes
  dependencies:
    - scotty
    - wai
    - warp


executables:
  left-ci:
    main: Main.hs
    source-dirs: app
    dependencies:
      - left-ci
      - warp



tests:
  unit:
    dependencies:
      - left-ci
      - HUnit
    main: Main.hs
    source-dirs: test/unit

  integration:
    dependencies:
      - left-ci
      - HUnit
      - wai
    main: Main.hs
    source-dirs: test/integration