name: left-ci
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - text
  - time
  - containers
  - sqlite-simple


library:
  source-dirs: src
  exposed-modules:
    - Config.ApplicationConfig
    - Config.Validator
    - Server
    - Server.Service
    - Server.Service.Persistent
    - Server.DataStore
    - Server.DataStore.Atomic
    - Server.DataStore.SQLiteStore
    - Server.DataStore.SQLiteSetup
    - Server.DataStore.TmpDir
    - Server.DataStore.SQLiteStore.CreateBuild
    - Server.DataStore.SQLiteStore.Types
    - Server.Routes
    - Server.Domain
  dependencies:
    - directory
    - network
    - scotty
    - wai
    - wai-middleware-static
    - http-types 
    - warp
    - aeson
    - bytestring
    - sqlite-simple
    - resource-pool
    - filepath
    - time
executables:
  left-ci:
    main: Main.hs
    source-dirs: app
    dependencies:
      - left-ci
      - warp
      - unix

tests:
  unit:
    dependencies:
      - left-ci
      - HUnit
    main: Main.hs
    source-dirs: test/unit

  integration:
    dependencies:
      - left-ci
      - HUnit
      - directory
      - network
      - wai
      - warp
      - bytestring
      - wai-extra
      - http-types
      - scotty
      - aeson
      - sqlite-simple
      - resource-pool
      - filepath
      - random
      - sqlite-simple
      - http-client
      - raw-strings-qq
    main: Main.hs
    source-dirs: test/integration

data-files:
  - site/static/**/*
  - site/js/lib/**/*
