name: left-ci
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers

library:
  source-dirs: src

tests:
  left-ci-test:
    main: Main.hs
    source-dirs: 
      - test
      - test/unit
      - test/integration
    dependencies:
      - HUnit
      - left-ci
